language : python
sudo: false
python:
    - "3.4"
before_install:
    - export LD_LIBRARY_PATH="/usr/local/lib/"
    - git clone https://github.com/lloyd/yajl.git
    - cd yajl && ./configure && make && make install

install: "pip install -r requirements.txt"
script: 
    - flake8 --max-line-length=120 vyked
    - py.test -v
