language : python
sudo: false
python:
    - "3.4"
before_install:
    - export LIBRARY_PATH=$HOME/.local/:$LIBRARY_PATH
    - git clone --depth=1 https://github.com/lloyd/yajl.git
    - cd yajl && ./configure --prefix=$HOME/.local/
    - cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local/lib && make && make install
    - cd ..

install: "pip install -r requirements.txt"
script: 
    - flake8 --max-line-length=120 vyked
    - py.test -v
